[package]
name = "kitsune_p2p_types"
version = "0.0.1"
description = "types subcrate for kitsune-p2p"
license = "Apache-2.0"
homepage = "https://apilium.com"
repository = "https://github.com/ApiliumCode/aingle"
documentation = "https://docs.rs/kitsune_p2p_types"
authors = ["Apilium Technologies <hello@apilium.com>"]
keywords = [ "aingle", "ai", "p2p", "sgd", "networking" ]
categories = [ "network-programming" ]
edition = "2018"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("test_utils"))'] }

[dependencies]
base64 = "0.21"
derive_more = "0.99.7"
futures = "0.3"
ghost_actor = { version = "0.3.0-alpha.1", features = ["test_utils"] }
lair_keystore_api = "0.0.11"
mockall = "0.11"
lru = "0.6.5"
nanoid = "0.4"
observability = { version = "0.1", package = "aingle-observability" }
once_cell = "1.4"
parking_lot = "0.12"
paste = "1.0"
rmp-serde = "0.15"
rustls = { workspace = true }
rustls-pki-types = "1"
serde = { version = "1", features = [ "derive", "rc" ] }
serde_bytes = "0.11"
serde_json = { version = "1", features = [ "preserve_order" ] }
shrinkwraprs = "0.3.0"
sysinfo = "0.37"
thiserror = "2.0"
tokio = { version = "1", features = [ "full" ] }
tokio-stream = { version = "0.1", features = [ "sync", "net" ] }
url = "2"
url2 = "0.0.6"

[dev-dependencies]
criterion = "0.5"
tracing-subscriber = "0.3"

[[bench]]
name = "api_thru"
harness = false

[features]
test_utils = []
