[package]
name = "aingle_wasm_test_utils"
version = "0.0.1"
description = "WASM test utilities for AIngle development"
license = "Apache-2.0"
repository = "https://github.com/ApiliumCode/aingle"
authors = ["Apilium Technologies <hello@apilium.com>"]
keywords = ["aingle", "wasm", "testing", "utilities"]
categories = ["development-tools::testing", "wasm"]
edition = "2021"

[lib]
name = "aingle_wasm_test_utils"
crate-type = [ "cdylib", "rlib" ]
path = "./src/lib.rs"

[features]
default = []
build = []
only_check = []


[dependencies]
ai_fixt = { path = "../../ai_fixt" }
 ai_hash = { version = ">=0.0.1", path = "../../ai_hash" }
aingle_types = { path = "../../aingle_types" }
aingle_zome_types = { version = ">=0.0.1", path = "../../aingle_zome_types" }
rand = "0.9"
strum = "0.26"
strum_macros = "0.26"
aingle_util = { version = "0.0.1", path = "../../aingle_util" }

[build-dependencies]
toml = "0.5"
walkdir = "2.3.1"
