[package]
name = "mr_bundle"
version = "0.0.1"
authors = ["Apilium Technologies <hello@apilium.com>"]
edition = "2018"
description = "Implements the un-/packing of bundles that either embed or reference a set of resources"
license = "Apache-2.0"
homepage = "https://apilium.com"
repository = "https://github.com/ApiliumCode/aingle"
documentation = "https://docs.rs/mr_bundle"

[dependencies]
bytes = "1.11"
derive_more = "0.99"
either = "1.5"
flate2 = "1.1"
aingle_util = { path = "../aingle_util", version = "0.0.1" }
futures = "0.3"
reqwest = "0.12"
rmp-serde = "1"
serde = { version = "1.0", features = [ "serde_derive", "derive" ] }
serde_bytes = "0.11"
serde_derive = "1.0"
thiserror = "2.0"

arbitrary = {version = "1.0", features = ["derive"], optional = true}
serde_yml = {version = "0.0.12", optional = true}

[dev-dependencies]
anyhow = "1.0"
matches = "0.1"
maplit = "1"
serde_yml = "0.0.12"
tokio = { version = "1", features = ["full"]}
tempdir = "0.3"

[features]

packing = [
  "serde_yml",
  "aingle_util/tokio",
]
