[package]
name = "kitsune_p2p_transport_quic"
version = "0.0.1"
description = "QUIC transport module for kitsune-p2p"
license = "Apache-2.0"
homepage = "https://apilium.com"
repository = "https://github.com/ApiliumCode/aingle"
documentation = "https://docs.rs/kitsune_p2p_transport_quic"
authors = ["Apilium Technologies <hello@apilium.com>"]
keywords = [ "aingle", "ai", "p2p", "sgd", "networking" ]
categories = [ "network-programming" ]
edition = "2018"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("test_utils"))'] }

[dependencies]
blake2b_simd = "1.0.3"
futures = "0.3"
if-addrs = "0.6"
kitsune_p2p_types = { version = "0.0.1", path = "../types" }
lair_keystore_api = "0.0.11"
nanoid = "0.4"
once_cell = "1.5.2"
quinn = "0.11"
rcgen = "0.13"
rustls = { workspace = true }
rustls-pki-types = "1"
serde = { version = "1.0", features = [ "derive" ] }
tokio = { version = "1", features = [ "full" ] }
tokio-util = { version = "0.7", features = [ "compat" ] }
